### ISSUE TITLE
vector.sum() return wrong result

### ISSUE THREAD

**Issue by prim** [allelos/vectors#20]
$ cat e.py
from vectors import Point, Vector
l = Vector(1, 1, 3)
c = Vector(1, 2, 3)
print l.sum(c)

$ python e.py
Vector(2.0, 2.0, 6.0)

**Comment by mshemuni** [comment]
I was able to regenerate the problem.

Here how the sum method works.

You have a list with 3 element (numbers) as self.vector attribute in Vector class.
When sum is called the code below is executed:

```
return (self.from_list([x+vector.vector[self.vector.index(x)]
                for x in self.vector]))
```

We shall change the line into loop:

```
for x in self.vector:
	x+vector.vector[self.vector.index(x)]
```

The problem is: when an element is selected by this loop, let's say first element, `self.vector.index(x)` will return the index in that value. Than `vector.vector[self.vector.index(x)]` would return the element of the other vector.

So in your example you ave a vector:

`l = 1, 1, 2`

`c = 1, 2, 3`

the line will get first element of l `1`, than find its index `0`, than get the 0th element of c `1`.
The trouble starts when loop goes to the second iteration.
the line will get second element `1`, than find its index `0` (index method would return the index of first found element), than get the 0th element of c again `1`.

My advice would be avoid vectors with repeated values. If you have a repeated element in your vector, reverse the sum order. since `v1 + v2 = v2 + v1` use:

```
from vectors import Point, Vector
l = Vector(1, 1, 3)
c = Vector(1, 2, 3)
print c.sum(l)

```

Or you can change the library itself which is nor reliable.
open file `[your env path]/lib/python3.7/site-packages/vectors/vectors.py`. Go to line `57`.
Change from:
```
        return (self.from_list([x+vector.vector[self.vector.index(x)]
                for x in self.vector]))
```
to:
```
        return (self.from_list([x+y
                for x, y in zip(self.vector, vector.vector)]))
```

Or install it from github:
```
git clone https://github.com/allelos/vectors vec
cd vec
python setup.py instal
```
